[package]
name = "rusty-tetris"
version = "0.0.2"
authors = [
    "bachm",
    "bvssvni <bvssvni@gmail.com>",
    "phideg <deglerp@googlemail.com>"
]

[[bin]]
name = "rusty_tetris"
path = "src/main.rs"


[dependencies]
piston = "0.1.5"
pistoncore-glutin_window = "0.2.0"
piston2d-opengl_graphics = "0.1.0"
piston2d-graphics = "0.1.4"
rand = "0.3.8"