[package]
name = "rusty-tetris"
version = "0.0.6"
authors = [
    "bachm",
    "bvssvni <bvssvni@gmail.com>",
    "phideg <deglerp@googlemail.com>"
]

[[bin]]
name = "rusty_tetris"
path = "src/main.rs"


[dependencies]
piston_window = "0.64"
piston-music = "0.19"
gfx_device_gl = "0.13"
find_folder = "0.3"
rand = "0.3"
clap = "2.22"
