[package]
name = "rusty-tetris"
version = "0.0.2"
authors = [
    "bachm",
    "bvssvni <bvssvni@gmail.com>",
    "phideg <deglerp@googlemail.com>"
]

[[bin]]
name = "rusty_tetris"
path = "src/main.rs"


[dependencies]
piston_window = "0.60.*"
gfx_device_gl = "0.12.*"
find_folder = "0.3.*"
rand = "0.3.*"
