[package]
name = "rusty-tetris"
version = "0.0.2"
authors = [
    "bachm",
    "bvssvni <bvssvni@gmail.com>",
    "phideg <deglerp@googlemail.com>"
]

[[bin]]
name = "rusty_tetris"
path = "src/main.rs"


[dependencies]
piston = "0.15.1"
pistoncore-glutin_window = "0.17.1"
piston2d-opengl_graphics = "0.19.0"
piston2d-graphics = "0.11.0"
rand = "0.3.12"
