[package]
name = "rusty-tetris"
version = "0.0.2"
authors = [
    "bachm",
    "bvssvni <bvssvni@gmail.com>",
    "phideg <deglerp@googlemail.com>"
]

[[bin]]
name = "rusty_tetris"
path = "src/main.rs"


[dependencies]
gfx_device_gl = "0.7.0"
piston_window = "0.33.0"
rand = "0.3.13"
